services:
  - type: web
    name: webscan-backend
    repo: https://github.com/Shak-Corp/WEB_SCAN
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webscan-db
          property: connectionString
    autoDeploy: true

  - type: web
    name: webscan-frontend
    repo: https://github.com/Shak-Corp/WEB_SCAN
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_ENDPOINT
        value: https://webscan-backend.onrender.com
    autoDeploy: true

  - type: psql
    name: webscan-db
